package exception;

public class Ex02 {

	public static void main(String[] args) {
		
		System.out.println("try - catch 시작");
		
		try {
			System.out.println("try 블록!");
		}
		catch(Exception e){
			System.out.println("예외가 발생???");
		}
		
		try {
			System.out.println(1 / 0); // 0으로 나누기 금지
			System.out.println("try블록!"); // 예외가 발생하면 실행이 안됨
		}
		catch(ArithmeticException ae) {
			System.out.println("예외가 발생!!!");
		}

	}

}
